#!/bin/bash

# Build a generic letter
# Ever option specified with V of M could also be specified
# in the letter metadata.

FILENAME=$(basename --suffix=.pandoc $1)

# Colors have to be specified by their HTML value.
ACCENTCOLOR=B93C5A
TEXTCOLOR=444444

pandoc ${FILENAME}.pandoc \
       --template=letter.latex \
       -o ${FILENAME}.pdf \
       -V fontfamily=mathpazo \
       -V textcolor=$TEXTCOLOR \
       -V accentcolor=$ACCENTCOLOR \
       -M classoption='fromalign=right' \
       -M classoption='foldmarks=false' \
       -M classoption='fromrule=aftername'
